[workspace]

members = [
    "cli",
    "client",
    "libsplinter",
    "splinterd",
    "examples/private_counter/cli",
    "examples/private_counter/service",
]
exclude = [
    "examples/private_xo",
]
