# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[features]
default = []

stable = ["default"]

experimental = [
    "circuit",
    "health",
    "database",
    "database-migrate-biome-credentials",
    "database-migrate-biome-notifications",
    "database-migrate-biome-user",
    "postgres",
]

circuit = ["reqwest", "serde_json", "splinter/sawtooth-signing-compat"]
health = ["reqwest", "serde_json"]

database = ["splinter/database", "diesel", "postgres"]
database-migrate-biome-user = ["splinter/biome-user", "database"]
database-migrate-biome-credentials = [
    "splinter/biome-credentials",
    "database-migrate-biome-user",
]
database-migrate-biome-notifications = [
    "splinter/biome-notifications",
    "database-migrate-biome-user",
]
postgres = [
    "diesel/postgres",
    "splinter/postgres",
]

[package]
name = "splinter-cli"
version = "0.3.9"
authors = ["Cargill Incorporated"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "splinter"
path = "src/main.rs"

[dependencies]
clap = "2"
diesel = { version = "1.0", features = ["postgres"], optional = true }
flexi_logger = "0.14"
libc = "0.2"
log = "0.4"
openssl = "0.10"
protobuf = "2"
reqwest = { version = "0.10", features = ["blocking", "json"], optional = true }
sawtooth-sdk = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version ="1.0", optional = true }
serde_yaml = "0.8"
splinter = { path = "../libsplinter" }

[package.metadata.deb]
maintainer = "The Splinter Team"
depends = "$auto"
maintainer-scripts = "packaging/ubuntu"
