# Copyright 2018-2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "splinter-cli"
version = "0.3.14"
authors = ["Cargill Incorporated"]
edition = "2018"
license = "Apache-2.0"
description = """\
    Splinter is a privacy-focused platform for distributed applications that \
    provides a blockchain-inspired networking environment for communication \
    and transactions between organizations.
"""

[[bin]]
name = "splinter"
path = "src/main.rs"

[dependencies]
clap = "2"
diesel = { version = "1.0", features = ["postgres"], optional = true }
dirs = { version = "2.0", optional = true }
flexi_logger = "0.14"
libc = "0.2"
log = "0.4"
openssl = "0.10"
protobuf = "2"
reqwest = { version = "0.10", features = ["blocking", "json"], optional = true }
sawtooth-sdk = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version ="1.0", optional = true }
serde_yaml = "0.8"
splinter = { path = "../libsplinter" }
whoami = { version = "0.7.0", optional = true }

[features]
default = []

stable = ["default"]

experimental = [
    "circuit",
    "circuit-template",
    "health",
    "database",
    "database-migrate-biome",
    "postgres",
    "keygen",
    "circuit-auth-type",
    "node-alias"
]

circuit = ["reqwest", "serde_json", "splinter/sawtooth-signing-compat", "dirs"]
circuit-auth-type = ["circuit"]
circuit-template = ["splinter/circuit-template", "circuit"]
database-migrate-biome = [
    "splinter/biome-credentials",
    "splinter/biome-key-management",
    "splinter/biome-notifications"
]
node-alias = ["dirs", "reqwest"]


health = ["reqwest", "serde_json"]
keygen = ["dirs", "whoami"]

database = ["splinter/database", "diesel", "postgres"]
postgres = [
    "diesel/postgres",
    "splinter/postgres",
]

[package.metadata.deb]
maintainer = "The Splinter Team"
depends = "$auto"
maintainer-scripts = "packaging/ubuntu"
assets = [
    ["packaging/man/*", "/usr/share/man/man1", "644"],
    ["target/release/splinter", "/usr/bin/splinter", "755"],
    ["packaging/scabbard_circuit_template.yaml", "/usr/share/splinter/circuit-templates/scabbard.yaml", "644"]
]
