# Copyright 2019 Bitwise, IO Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "grid-daemon"
version = "0.1.0"
authors = ["Contributors to Hyperledger Grid"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "0.7"
clap = "2"
ctrlc = "3.0"
diesel = { version = "1.0.0", features = ["postgres", "r2d2", "serde_json"] }
diesel_migrations = "1.4"
grid-sdk = { path = "../sdk" }
log = "0.4"
protobuf = "2"
sawtooth-sdk = { git = "https://github.com/hyperledger/sawtooth-sdk-rust" }
simple_logger = "1.0"
futures = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.6", features = ["v4"] }
url = "1.7.1"
base64 = "0.10"
byteorder = "1"

[features]
test-api = []

[[bin]]
name = "gridd"
path = "src/main.rs"
