# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2.2"

services:

  splinter-node-0:
    image: splinterd:latest
    build:
        context: ../..
        dockerfile: ./splinterd/Dockerfile
    expose:
      - 8043
      - 8044
    volumes:
      - ./demo_state:/splinter_state
    command: >
      bash -c "
        /splinterd -vv \
                --transport raw \
                --storage yaml \
                --service-endpoint 0.0.0.0:8043 \
                --network-endpoint 0.0.0.0:8044 \
                --node-id 012
      "
    environment:
      SPLINTER_STATE_DIR: /splinter_state

  splinter-node-1:
    image: splinterd:latest
    build:
        context: ../..
        dockerfile: ./splinterd/Dockerfile
    expose:
      - 8045
      - 8046
    volumes:
      - ./demo_state:/splinter_state
    command: >
      bash -c "
        /splinterd -vv \
                --transport raw \
                --storage yaml \
                --service-endpoint 0.0.0.0:8045 \
                --network-endpoint 0.0.0.0:8046 \
                --node-id 345
      "
    environment:
      SPLINTER_STATE_DIR: /splinter_state

  splinter-node-2:
    image: splinterd:latest
    build:
        context: ../..
        dockerfile: ./splinterd/Dockerfile
    expose:
      - 8047
      - 8048
    volumes:
      - ./demo_state:/splinter_state
    command: >
      bash -c "
        /splinterd -vv \
                --transport raw \
                --storage yaml \
                --service-endpoint 0.0.0.0:8047 \
                --network-endpoint 0.0.0.0:8048 \
                --node-id 678
      "
    environment:
      SPLINTER_STATE_DIR: /splinter_state

  private-counter-service-a:
    image: private-counter:latest
    container_name: private-counter-service-a
    build:
        context: ../..
        dockerfile: ./examples/private_counter/service/Dockerfile
    expose:
        - 8000
    ports:
        - "8008:8000"
    command: >
        bash -c "
          sleep 2;
          private-counter -vv \
                      --bind 0.0.0.0:8000 \
                      --circuit alpha \
                      --service-id service_a \
                      --verifier service_b \
                      --verifier service_c \
                      --connect splinter-node-0:8043
        "

  private-counter-service-b:
    image: private-counter:latest
    container_name: private-counter-service-b
    build:
        context: ../..
        dockerfile: ./examples/private_counter/service/Dockerfile
    expose:
        - 8000
    ports:
        - "8009:8000"
    command: >
        bash -c "
          sleep 2;
          private-counter -vv \
                      --bind 0.0.0.0:8000 \
                      --circuit alpha \
                      --service-id service_b \
                      --verifier service_a \
                      --verifier service_c \
                      --connect splinter-node-1:8045
        "

  private-counter-service-c:
    image: private-counter:latest
    container_name: private-counter-service-c
    build:
        context: ../..
        dockerfile: ./examples/private_counter/service/Dockerfile
    expose:
        - 8000
    ports:
        - "8010:8000"
    command: >
        bash -c "
          sleep 2;
          private-counter -vv \
                      --bind 0.0.0.0:8000 \
                      --circuit alpha \
                      --service-id service_c \
                      --verifier service_a \
                      --verifier service_b \
                      --connect splinter-node-2:8047
        "

  pcounter:
    image: pcounter:latest
    container_name: pcounter-local
    build:
        context: .
        dockerfile: ./cli/Dockerfile
    init: true
    entrypoint: |
      bash -c "
        tail -f /dev/null
      "
    stop_signal: SIGKILL
