# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[features]
zmq-transport = ["zmq"]
ursa-compat = ["ursa"]
sawtooth-signing-compat = ["sawtooth-sdk"]
events = ["hyper", "tokio", "awc"]

[package]
name = "splinter"
version = "0.3.5"
authors = ["Cargill Incorporated"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
actix = { version = "0.8", default-features = false }
actix-web = { version = "1.0", default-features = false, features = ["flate2-zlib"] }
flate2 = "1.0.10"
actix-service = "0.4"
actix-http = {version = "0.2", features = ["flate2-zlib"] }
actix-web-actors = "1.0"
futures = "0.1"
atomicwrites = "0.2"
log = "0.3.0"
byteorder = "1"
url = "1.7.1"
openssl = "0.10"
mio = "0.6"
sawtooth-sabre = "0.4"
sawtooth-sdk = { version = "0.3", optional = true }
serde = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0"
serde_json = "1.0"
transact = { version = "0.1", features = ["sawtooth-compat"] }
mio-extras = "2"
crossbeam-channel = "0.3"
uuid = { version = "0.7", features = ["v4"]}
protobuf = "2"
zmq = { version = "0.9", optional = true }
ursa = { version = "0.1", optional = true }
hyper = { version = "0.12", optional = true }
tokio = { version = "0.1.22", optional = true }
awc = { version = "0.2", optional = true }

[dev-dependencies]
tempdir = "0.3"

[build-dependencies]
protoc-rust = "2"
glob = "0.2"
