[package]
name = "griddle"
version = "0.3.2"
authors = ["Contributors to Hyperledger Grid"]
edition = "2018"
license = "Apache-2.0"
description = "Grid integration component"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "3", default-features = false }
clap = "2.33.3"
diesel = { version = "1.0", features = ["r2d2"], optional = true }
flexi_logger = "0.17"
grid-sdk = { path = "../sdk", features = ["rest-api-actix-web-3", "rest-api-actix-web-3-run", "batch-processor"] }
log = "0.4"
users = "0.11"

[features]
default = []

stable = [
    # The stable feature extends default:
    "default",
    # The following features are stable:
]

experimental = [
    # The experimental feature extends stable:
    "stable",
    # The following features are experimental:
    "database-postgres",
    "database-sqlite",
]

database-postgres = ["diesel", "grid-sdk/postgres"]
database-sqlite = ["diesel", "grid-sdk/sqlite"]
