# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.7"

services:

  splinterd:
    image: splinterd:${ISOLATION_ID}
    volumes:
      - ../../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  splinter-cli:
    image: splinter-cli:${ISOLATION_ID}
    volumes:
      - ../../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

# ---==== examples ====---

  private_xo:
    image: private_xo:${ISOLATION_ID}
    volumes:
      - ../../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  private_counter_cli:
    image: private_counter_cli:${ISOLATION_ID}
    volumes:
      - ../../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  private_counter_service:
    image: private_counter_service:${ISOLATION_ID}
    volumes:
      - ../../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

# ---==== gameroom components ====---

  gameroomd:
    image: gameroomd:${ISOLATION_ID}
    volumes:
      - ../../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  gameroom-app-acme:
    image: gameroom-app-acme:${ISOLATION_ID}
    volumes:
      - ../../build/html:/build/html
    command: |
      bash -c "
        cp /tmp/*.tar.gz /build/html
      "

  gameroom-app-bubba:
    image: gameroom-app-bubba:${ISOLATION_ID}
    volumes:
      - ../../build/html:/build/html
    command: |
      bash -c "
        cp /tmp/*.tar.gz /build/html
      "
